"""Utility functions and helpers."""

from video2d3d.utils.config import (
    Config,
    get_config,
    get_config_path,
    get_environment,
    load_config,
    reload_config,
)
from video2d3d.utils.error_recovery import (  # Configuration; Exceptions; Classes; Decorators; Functions; Constants; Error Detection Constants
    CUDA_ERROR_SUBSTRINGS,
    DEFAULT_BACKOFF_FACTOR,
    DEFAULT_CPU_FALLBACK_ENABLED,
    DEFAULT_MAX_RETRIES,
    DEFAULT_MAX_RETRY_DELAY_SECONDS,
    DEFAULT_MODEL_FALLBACK_CHAIN,
    DEFAULT_RETRY_DELAY_SECONDS,
    DEFAULT_SKIP_ON_MAX_RETRIES,
    OOM_ERROR_SUBSTRINGS,
    TIMEOUT_ERROR_SUBSTRINGS,
    AllModelsFailedError,
    BackoffStrategy,
    ErrorRecoveryConfig,
    FrameRecoveryFailedError,
    FrameRecoveryManager,
    MaxRetriesExceededError,
    ModelFallbackChain,
    RecoveryContext,
    RecoveryError,
    RecoveryStats,
    RecoveryStrategy,
    create_recovery_config_from_dict,
    create_recovery_decorator,
    recovery_with_fallback,
)
from video2d3d.utils.gpu import (  # Classes; Exceptions; Functions
    DeviceSelection,
    DeviceType,
    GPUConfig,
    GPUError,
    GPUInfo,
    OutOfMemoryError,
    clear_gpu_memory,
    compute_optimal_batch_size,
    configure_cudnn,
    create_pinned_tensor,
    estimate_memory_requirement,
    get_all_gpu_info,
    get_device_count,
    get_gpu_info,
    get_memory_usage,
    is_cuda_available,
    is_mps_available,
    is_torch_available,
    select_best_gpu,
    select_device,
    setup_device,
    transfer_to_cpu,
    transfer_to_gpu,
    with_oom_retry,
)
from video2d3d.utils.logger import (
    LogLevel,
    configure_logging,
    get_logger,
    is_logging_configured,
    log_context,
    log_exception,
    log_memory_usage,
    log_model_inference,
    log_performance,
    log_video_processing,
    set_log_level,
)
from video2d3d.utils.memory_monitor import (  # Classes and Enums; Type Aliases; Functions; Context Managers; Constants
    BYTES_PER_GB,
    BYTES_PER_MB,
    DEFAULT_CRITICAL_THRESHOLD,
    DEFAULT_EMERGENCY_THRESHOLD,
    DEFAULT_GC_CRITICAL_THRESHOLD,
    DEFAULT_GC_WARNING_THRESHOLD,
    DEFAULT_MONITOR_INTERVAL,
    DEFAULT_WARNING_THRESHOLD,
    MemoryInfo,
    MemoryMonitor,
    MemoryMonitorConfig,
    MemoryWarningCallback,
    MemoryWarningLevel,
    format_memory_size,
    get_current_memory_info,
    get_memory_monitor,
    memory_monitor_context,
)
from video2d3d.utils.profiler import (  # Classes; Decorators; Context Managers; Functions
    ComponentStats,
    PipelineProfiler,
    Profiler,
    ProfilerResult,
    clear_profiler,
    get_all_profilers,
    get_profiler,
    profile_block,
    profile_component,
    timed_execution,
)

__all__ = [
    # Config
    "Config",
    "get_config",
    "get_config_path",
    "get_environment",
    "load_config",
    "reload_config",
    # Logging
    "LogLevel",
    "configure_logging",
    "get_logger",
    "log_context",
    "log_exception",
    "log_performance",
    "log_video_processing",
    "log_model_inference",
    "log_memory_usage",
    "set_log_level",
    "is_logging_configured",
    # GPU
    "GPUConfig",
    "GPUInfo",
    "DeviceSelection",
    "DeviceType",
    "GPUError",
    "OutOfMemoryError",
    "is_torch_available",
    "is_cuda_available",
    "is_mps_available",
    "get_device_count",
    "get_gpu_info",
    "get_all_gpu_info",
    "select_best_gpu",
    "select_device",
    "clear_gpu_memory",
    "get_memory_usage",
    "estimate_memory_requirement",
    "compute_optimal_batch_size",
    "create_pinned_tensor",
    "transfer_to_gpu",
    "transfer_to_cpu",
    "with_oom_retry",
    "configure_cudnn",
    "setup_device",
    # Error Recovery - Configuration
    "ErrorRecoveryConfig",
    "RecoveryStats",
    "RecoveryStrategy",
    "BackoffStrategy",
    # Error Recovery - Exceptions
    "RecoveryError",
    "MaxRetriesExceededError",
    "AllModelsFailedError",
    "FrameRecoveryFailedError",
    # Error Recovery - Classes
    "FrameRecoveryManager",
    "ModelFallbackChain",
    "RecoveryContext",
    # Error Recovery - Decorators
    "recovery_with_fallback",
    "create_recovery_decorator",
    # Error Recovery - Functions
    "create_recovery_config_from_dict",
    # Error Recovery - Constants
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_RETRY_DELAY_SECONDS",
    "DEFAULT_BACKOFF_FACTOR",
    "DEFAULT_MAX_RETRY_DELAY_SECONDS",
    "DEFAULT_MODEL_FALLBACK_CHAIN",
    "DEFAULT_CPU_FALLBACK_ENABLED",
    "DEFAULT_SKIP_ON_MAX_RETRIES",
    # Error Detection Constants
    "OOM_ERROR_SUBSTRINGS",
    "CUDA_ERROR_SUBSTRINGS",
    "TIMEOUT_ERROR_SUBSTRINGS",
    # Memory Monitor
    "MemoryMonitor",
    "MemoryInfo",
    "MemoryMonitorConfig",
    "MemoryWarningLevel",
    "MemoryWarningCallback",
    "get_memory_monitor",
    "get_current_memory_info",
    "format_memory_size",
    "memory_monitor_context",
    "BYTES_PER_MB",
    "BYTES_PER_GB",
    "DEFAULT_WARNING_THRESHOLD",
    "DEFAULT_CRITICAL_THRESHOLD",
    "DEFAULT_EMERGENCY_THRESHOLD",
    "DEFAULT_MONITOR_INTERVAL",
    "DEFAULT_GC_WARNING_THRESHOLD",
    # Profiler
    "Profiler",
    "PipelineProfiler",
    "ComponentStats",
    "ProfilerResult",
    "profile_component",
    "profile_block",
    "get_profiler",
    "clear_profiler",
    "get_all_profilers",
    "timed_execution",
]
